/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 milkcartons-baked.glb 
*/

import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

export function Model(props) {
  const { nodes } = useGLTF('/milkcartons-baked.glb');
  const bakedTexture = useTexture('/milkcarton-texture-bake-copy.png');
  nodes.carton.geometry.attributes.uv = nodes.carton.geometry.attributes.uv1; // overwrite pme iv fpr now
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.carton.geometry}>
        <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.ground.geometry}>
        <meshBasicMaterial
          map={bakedTexture}
          map-flipY={false}
          transparent={true}
        />
      </mesh>
    </group>
  );
}

useTexture.preload('/milkcarton-texture-bake-copy.png');
useGLTF.preload('/milkcartons-baked.glb');
