/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 milkcartons3.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/milkcartons4.glb');
  return <mesh geometry={nodes['3'].geometry} {...props} />;
}

useGLTF.preload('/milkcartons4.glb');
