/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 milkcartons.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/milkcartons.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3'].geometry}>
        <meshStandardMaterial />
      </mesh>
    </group>
  );
}

useGLTF.preload('/milkcartons.glb');
